version: '3'

services:
  database:
    container_name: database
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_ADDRESS}
    ports:
      - "3307:3306"
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
    networks:
      - bridge
  rest:
    container_name: homebudget
    build: .
    env_file:
      - db_variables.env
    ports:
      - "8081:8080"
    depends_on:
      - database
    networks:
      - bridge

networks:
  bridge:




